create new user model CVBUser
ahmdhjj92/cv-builder pull request #9
Opened 2021-10-16 16:01 UTC by ahmdhjj92

2021-10-16 19:33 UTC, naz-hage requested changes

2021-10-16 19:33 UTC, naz-hage commented on cv_builder/users/models.py
> +            password=password
Password cannot be saved as plain text.  This is something that can be addressed later.  This is a sample  : https://stackoverflow.com/questions/37308246/django-how-to-save-my-hashed-password

2021-10-17 17:21 UTC, ahmdhjj92 commented
@naz-hage Since this commit introduces a different user model, you may need to delete your existing database `db.sqlite3` then run `python3 manage.py makemigrations` and `python3 manage.py migrate` commands. I have already deleted old migrations to prevent conflicts. In order to access admin page and check changes, run `python3 manage.py createsuperuser` to create a new admin account.

2021-11-07 09:06 UTC, ahmdhjj92 commented
Issue #8 requirements should now be met after the last commit

2021-11-14 14:43 UTC, merged